import { Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";

const FONT = Zen_Maru_Gothic({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ja">
            <body className={FONT.className}>{children}</body>
        </html>
    );
}
